name: LeeesNC
version: 10.1.0
main: Leee.nc.Main
api-version: 1.16
authors: [Nate, Legault, AlexProgrammerDE]
description: Leees Name Colour Plugin
website: https://www.6b6t.org
commands:
  nc:
    description: Change your name color.
    aliases: [namecolor, namecolour]
permissions:
  Leee.nc:
    description: Gives access to changing name color via the /nc command